packages:
  github/moura95/meli-api/internal/repository:
    interfaces:
      Querier:
        config:
          dir: "internal/repository/"
          filename: "querier_mock.go"
          inpackage: True
          with-expecter: True
        configs:
          - mockname: "QuerierMocked"
