// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package repository

import (
	"database/sql"
	"time"
)

type Category struct {
	ID       int32
	Name     string
	ParentID sql.NullInt32
}

type SeveritiesLevel struct {
	ID          int32
	Description string
}

type Ticket struct {
	ID            int32
	Title         string
	Status        string
	Description   string
	SeverityID    int32
	CategoryID    int32
	SubcategoryID sql.NullInt32
	CreatedAt     time.Time
	UpdatedAt     time.Time
	CompletedAt   sql.NullTime
	UserID        sql.NullInt32
}
