// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package repository

import (
	"database/sql"
	"time"
)

type Severity struct {
	ID          int32
	Level       int32
	Description string
}

type Ticket struct {
	ID          int32
	Title       string
	Status      string
	Description string
	SeverityID  int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
	CompletedAt sql.NullTime
}
