name: Deploy to Cloud Run
on:
  push:
    branches:
      - main
      - feature/devops
env:
  PROJECT_ID: 366701
  GAR_LOCATION: gcr.io/moura-366701
  SERVICE: meli-api
  REGION: southamerica-east1

jobs:
  cloudrunProd:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |-
          docker build -t gcr.io/moura-366701/meli-api -t latest .

      - name: Login to GCR
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.SERVICE_ACCOUNT_KEYS }}

      - name: Push to Artifact Registry
        run: |-
          docker push gcr.io/moura-366701/meli-api:latest

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          image: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{ github.sha }}